workspace(name="computer-system")

#load the go rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive","http_file")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

http_archive(
     name = "com_google_googletest",
     urls = ["https://github.com/google/googletest/archive/release-1.8.1.tar.gz"],
     strip_prefix = "googletest-release-1.8.1",
)

http_archive(
      name = "com_github_gflags_gflags",
      strip_prefix = "gflags-46f73f88b18aee341538c0dfc22b1710a6abedef",
      url = "https://github.com/gflags/gflags/archive/46f73f88b18aee341538c0dfc22b1710a6abedef.tar.gz",
)

# Google Benchmark
http_archive(
    name = "benchmark",
    strip_prefix = "v1.4.1",
    url = "https://github.com/google/benchmark/archive/v1.4.1.tar.gz"
)

# cpplint from google style guide
new_git_repository(
    name = "google_styleguide",
    build_file = "third_party/google_styleguide.BUILD",
    commit = "159b4c81bbca97a9ca00f1195a37174388398a67",
    remote = "https://github.com/google/styleguide.git"
)


